name: D PROD WITHOUT ARCHIVE

on:
  workflow_dispatch:
    
jobs:
  deploy:
    if: github.repository == 'htw-imi-showtime/showtime-website'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: false
    - name: Get Theme
      run: |
        git submodule update --init themes/showtime-theme-2021
    - name: Hugo setup
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.115.1'
        extended: true

    - name: Build
      run: |
        hugo \
          --environment production \
          --minify

    - name: Deploy
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SCP_HOST }}
        username: ${{ secrets.SCP_USERNAME }}
        key: ${{ secrets.SCP_KEY }}
        source: public/
        target: /var/www/html/
        rm: true
